language: cpp
compiler:
    - gcc
before_install:
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "yast2-core-dev yast2-devtools doxygen yast2-testsuite libdbus-1-dev libpolkit-gobject-1-dev python-dbus" -g ruby-dbus
script:
    - make -f Makefile.cvs
    - make
    - sudo make install
    - make check

